import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import FormGroup from "~/components/FormGroup";
import Input from "~/components/Input";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  }

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    // TODO: submit the form data to the backend
  }

  return (
    <>
      <Head>
        <title>Generate Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form
          action=""
          className="flex flex-col gap-4"
          onSubmit={handleFormSubmit}
        >
          <FormGroup>
            <label htmlFor="">Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")} />
          </FormGroup>

          <button className="rounded bg-blue-500 px-4 py-2 hover:bg-blue-300">
            Submit
          </button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;
