import { type NextPage } from "next";
import Head from "next/head";

import Image from "next/image";
import PrimaryLinkButton from "~/components/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="mt-40 grid grid-cols-2 gap-12 px-8">
      <div className="flex flex-col items-center justify-center gap-6">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-2xl">
          Use AI to generate icons instead of paying a designer and waiting for
          them to create them for you.
        </p>
        <PrimaryLinkButton href={"/generate"} className="self-start">
          Generated your icons
        </PrimaryLinkButton>
      </div>
      <Image
        src={"/banner.png"}
        className="rounded-lg bg-cover bg-center"
        alt="banner hero"
        width="600"
        height="600"
      />
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Creator App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
